# Generated by Django 4.1.7 on 2023-03-07 07:40

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('8f4ce513-eeb3-4f40-9eb6-c2d18f3e7249'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128)),
                ('mobile_num', models.IntegerField()),
                ('admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shopping', models.ManyToManyField(to='products.product')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
