# Generated by Django 4.1.7 on 2023-03-07 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('36a1e57a-5015-485b-842a-85e48ef5f109'), editable=False, primary_key=True, serialize=False),
        ),
    ]
