# Generated by Django 4.1.7 on 2023-03-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategories',
            table='categories_product',
        ),
    ]
