# Generated by Django 4.1.7 on 2023-03-07 07:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField()),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('category', models.ManyToManyField(to='products.categorys')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
