# Generated by Django 4.1.7 on 2023-03-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_categories',
        ),
    ]
